language: node_js

addons:
  chrome: stable

node_js:
   - node # will use latest node

script: # the build step
   - npm run build
   - npm run lint
   - npm run test.ci

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change
