language: node_js

node_js:
   - node # will use latest node

script: # the build step
   - npm build
   - npm test

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change
