sudo: false

language: node_js
node_js:
  - '12'

cache: yarn

install:
  - yarn --frozen-lockfile --non-interactive --no-progress

script:
  # lint
  - yarn run demo:lint:check
  - yarn run prettier:check
  # tests
  - yarn run lib:test:ci
  - yarn run lib:test:types
  # build
  - yarn run lib:build:prod
  - cp README.md LICENSE dist/ngrx-action-mapper

deploy:
  - provider: script
    skip_cleanup: true
    script: yarn semantic-release
    on:
      branch: master
